spread:
  sheet:
    id: 12mkuSN-O_mfbNPhG9QN5EXZPiHKSkPGJZZ3_V99yPSo

logging:
  level:
    root: info

spring:
  main:
    web-application-type: none

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: false
