name: cron

on:
  schedule:
    # 매일 매시간 00분에 실행
    - cron: '0 * * * *'
  # workflow_dispatch - 수동 실행을 위해 사용
  workflow_dispatch:

jobs:
  cron:
    runs-on: self-hosted
    steps:
      - name: Run Application
        run: java -jar google-sheet-practice.jar
